# Generated by Django 4.2.28 on 2026-03-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_deleted_at_region_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
