# Generated by Django 4.2.28 on 2026-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_region_created_by_region_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='area_sq_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in square kilometers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='boundary_geojson',
            field=models.JSONField(blank=True, help_text='GeoJSON boundary data for displaying region on map', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='population',
            field=models.IntegerField(blank=True, help_text='Estimated population', null=True),
        ),
    ]
