# Generated by Django 4.2.28 on 2026-03-19 08:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='partner',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='partner',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main/cover image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='partner',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for SEO and accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Secondary/WhatsApp number', max_length=30),
        ),
        migrations.AddField(
            model_name='partner',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='partner',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number (with country code)', max_length=30),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Partner logo', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, help_text='Official website URL'),
        ),
    ]
