# Generated by Django 4.2.28 on 2026-03-19 05:31

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('url', models.URLField(blank=True, help_text='External CDN/YouTube link')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('360_photo', '360 Photo'), ('drone', 'Drone Footage'), ('audio', 'Audio')], default='image', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(help_text='SEO + accessibility (required)', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Shown below media')),
                ('credit', models.CharField(blank=True, help_text='Photographer/videographer name', max_length=200)),
                ('credit_url', models.URLField(blank=True, help_text="Link to creator's portfolio")),
                ('license', models.CharField(choices=[('CC0', 'CC0'), ('CC-BY', 'CC-BY'), ('CC-BY-SA', 'CC-BY-SA'), ('proprietary', 'Proprietary')], default='proprietary', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_cover', models.BooleanField(default=False, help_text='Main/hero image')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in gallery highlight')),
                ('sort_order', models.IntegerField(default=0, help_text='Ordering in gallery')),
                ('width', models.IntegerField(blank=True, help_text='Pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Pixels', null=True)),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('taken_at', models.DateField(blank=True, help_text='When photo was taken', null=True)),
                ('location_name', models.CharField(blank=True, help_text='e.g. "Uhuru Peak, Kilimanjaro"', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='media_media_content_c23fc6_idx')],
            },
        ),
    ]
