# Generated by Django 4.2.28 on 2026-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alt_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='credit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='credit_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='taken_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
