# Generated by Django 4.2.28 on 2026-03-19 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(blank=True, help_text='Email address (required for anonymous)', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Full name (required for anonymous)', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user (if authenticated)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
