# Generated by Django 4.2.28 on 2026-03-19 05:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
                ('schema_type', models.CharField(blank=True, choices=[('TouristAttraction', 'Tourist Attraction'), ('Article', 'Article'), ('Person', 'Person'), ('Organization', 'Organization')], max_length=50)),
                ('schema_json', models.JSONField(blank=True, help_text='Full JSON-LD structured data', null=True)),
                ('no_index', models.BooleanField(default=False, help_text='Hide from search engines')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2)),
                ('sitemap_changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=20)),
                ('username', models.CharField(help_text='Public @handle', max_length=150, unique=True)),
                ('display_name', models.CharField(help_text='Full public name', max_length=200)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('avatar_alt', models.CharField(blank=True, help_text='Alt text for avatar', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short bio (280 chars)', max_length=280)),
                ('job_title', models.CharField(blank=True, help_text='e.g. "Wildlife Photographer"', max_length=150)),
                ('organisation', models.CharField(blank=True, help_text='e.g. "Serengeti Research Institute"', max_length=200)),
                ('expertise', models.CharField(blank=True, choices=[('wildlife', 'Wildlife'), ('photography', 'Photography'), ('hiking', 'Hiking'), ('culture', 'Culture'), ('marine', 'Marine'), ('geology', 'Geology')], max_length=50)),
                ('website', models.URLField(blank=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email_public', models.EmailField(blank=True, help_text='Optional public email', max_length=254)),
                ('location_city', models.CharField(blank=True, help_text='e.g. "Arusha"', max_length=100)),
                ('location_country', models.CharField(default='Tanzania', max_length=100)),
                ('attractions_created', models.IntegerField(default=0)),
                ('attractions_edited', models.IntegerField(default=0)),
                ('media_uploaded', models.IntegerField(default=0)),
                ('articles_written', models.IntegerField(default=0)),
                ('species_added', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True, help_text='Public profile page visible')),
                ('is_verified_creator', models.BooleanField(default=False, help_text='Xenohuru verified badge')),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
