# Generated by Django 4.2.28 on 2026-03-19 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
