# Generated by Django 4.2.28 on 2026-03-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('media', '0001_initial'),
        ('attractions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_attractions',
            field=models.ManyToManyField(blank=True, help_text='Attractions mentioned or featured in this article', related_name='blog_articles', to='attractions.attraction'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published'], name='blog_articl_is_publ_0f077c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='blog_articl_publish_cc3c64_idx'),
        ),
    ]
