# Generated by Django 4.2.28 on 2026-03-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
