# Generated by Django 4.2.28 on 2026-03-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_deleted_at_article_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
