# Generated by Django 4.2.28 on 2026-03-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
