# Generated by Django 4.2.28 on 2026-03-19 08:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
        ('blog', '0005_alter_article_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for SEO and accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main/cover image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Deprecated: Use status field instead'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this content was published', null=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='blog_articl_status_57fc64_idx'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='core.tag'),
        ),
    ]
