# Generated by Django 4.2.28 on 2026-03-19 08:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_region_meta_description_and_more'),
        ('core', '0002_tag'),
        ('operators', '0004_alter_touroperator_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperator',
            name='address',
            field=models.CharField(blank=True, help_text='Office physical address', max_length=500),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='city',
            field=models.CharField(blank=True, help_text='Office city', max_length=100),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main/cover image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for SEO and accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Mark as free if no entrance fee'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office GPS latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office GPS longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Secondary/WhatsApp number', max_length=30),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Primary operating region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_operators', to='regions.region'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tour_operators', to='core.tag'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number (with country code)', max_length=30),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Company logo', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='website',
            field=models.URLField(blank=True, help_text='Official website URL'),
        ),
    ]
