# Generated by Django 4.2.28 on 2026-04-06 17:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_touroperator_address_touroperator_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroperator',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
