# Generated by Django 4.2.28 on 2026-03-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('apparent_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('weather_code', models.IntegerField(null=True)),
                ('cloud_cover', models.IntegerField(null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('monthly_temperature', models.JSONField(blank=True, default=dict)),
                ('monthly_precipitation', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('attraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='attractions.attraction')),
            ],
            options={
                'verbose_name_plural': 'Weather cache',
            },
        ),
        migrations.CreateModel(
            name='SeasonalWeatherPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_type', models.CharField(choices=[('dry', 'Dry Season'), ('short_rain', 'Short Rain Season'), ('long_rain', 'Long Rain Season')], max_length=20)),
                ('start_month', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('avg_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_rainfall', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_patterns', to='attractions.attraction')),
            ],
            options={
                'ordering': ['start_month'],
            },
        ),
    ]
