# Generated by Django 4.2.28 on 2026-03-19 05:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
                ('schema_type', models.CharField(blank=True, choices=[('TouristAttraction', 'Tourist Attraction'), ('Article', 'Article'), ('Person', 'Person'), ('Organization', 'Organization')], max_length=50)),
                ('schema_json', models.JSONField(blank=True, help_text='Full JSON-LD structured data', null=True)),
                ('no_index', models.BooleanField(default=False, help_text='Hide from search engines')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2)),
                ('sitemap_changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('mountain', 'Mountain'), ('beach', 'Beach'), ('wildlife', 'Wildlife Safari'), ('cultural', 'Cultural Site'), ('historical', 'Historical Site'), ('adventure', 'Adventure Activity'), ('national_park', 'National Park'), ('island', 'Island'), ('waterfall', 'Waterfall'), ('lake', 'Lake'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.IntegerField(blank=True, help_text='Altitude in meters', null=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult'), ('extreme', 'Extreme')], max_length=20)),
                ('access_info', models.TextField(help_text='How to reach this attraction')),
                ('nearest_airport', models.CharField(blank=True, max_length=100)),
                ('distance_from_airport', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km', max_digits=6, null=True)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('seasonal_availability', models.TextField(help_text='When is this attraction accessible?')),
                ('estimated_duration', models.CharField(help_text='e.g., 5-7 days, 2 hours', max_length=100)),
                ('entrance_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee in USD', max_digits=10, null=True)),
                ('requires_guide', models.BooleanField(default=False)),
                ('requires_permit', models.BooleanField(default=False)),
                ('featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttractionBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_type', models.CharField(choices=[('polygon', 'Polygon'), ('circle', 'Circle'), ('corridor', 'Corridor'), ('point_cluster', 'Point Cluster')], max_length=50)),
                ('geojson', models.JSONField(blank=True, help_text='Full GeoJSON polygon/multipolygon', null=True)),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bbox_north', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_south', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_east', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bbox_west', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perimeter_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevation_min_m', models.IntegerField(blank=True, null=True)),
                ('elevation_max_m', models.IntegerField(blank=True, null=True)),
                ('main_gate_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_gate_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_gate_name', models.CharField(blank=True, max_length=200)),
                ('entry_points', models.JSONField(blank=True, help_text='List of {name, lat, lng, type}', null=True)),
                ('zones', models.JSONField(blank=True, help_text='[{name, description, geojson}]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attraction Boundaries',
            },
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttractionTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('citation_type', models.CharField(choices=[('research_paper', 'Research Paper'), ('book', 'Book'), ('government_report', 'Government Report'), ('news', 'News Article'), ('website', 'Website'), ('ngo_report', 'NGO Report'), ('documentary', 'Documentary')], max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('accessed_date', models.DateField(blank=True, null=True)),
                ('formatted_citation', models.TextField(blank=True, help_text='Auto-generated APA format')),
                ('is_primary_source', models.BooleanField(default=False)),
                ('trust_score', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NearestTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('airport', 'Airport'), ('train_station', 'Train Station'), ('bus_terminal', 'Bus Terminal'), ('major_city', 'Major City / Town'), ('port', 'Port / Ferry Terminal'), ('ferry', 'Ferry Stop')], max_length=20)),
                ('name', models.CharField(help_text='e.g., Kilimanjaro International Airport', max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance in km', max_digits=7)),
                ('travel_time_minutes', models.IntegerField(blank=True, help_text='Approximate travel time in minutes', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional info, transport options, notes')),
                ('is_recommended', models.BooleanField(default=False, help_text='Recommended route/facility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_facilities', to='attractions.attraction')),
            ],
            options={
                'verbose_name': 'Nearest Transport',
                'verbose_name_plural': 'Nearest Transports',
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='EndemicSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('conservation_status', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], default='LC', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endemic_species', to='attractions.attraction')),
            ],
            options={
                'verbose_name_plural': 'Endemic Species',
                'ordering': ['common_name'],
            },
        ),
    ]
