# Generated by Django 4.2.28 on 2026-03-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='citations', to='blog.article'),
        ),
        migrations.AddField(
            model_name='citation',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='citations', to='attractions.attraction'),
        ),
        migrations.AddField(
            model_name='citation',
            name='endemic_species',
            field=models.ManyToManyField(blank=True, related_name='citations', to='attractions.endemicspecies'),
        ),
    ]
