# Generated by Django 4.2.28 on 2026-03-19 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('media', '0001_initial'),
        ('attractions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='citations', to='regions.region'),
        ),
        migrations.AddField(
            model_name='attractiontip',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='attractions.attraction'),
        ),
        migrations.AddField(
            model_name='attractiontip',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attractionimage',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractions.attraction'),
        ),
        migrations.AddField(
            model_name='attractionboundary',
            name='attraction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boundary', to='attractions.attraction'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attraction',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='regions.region'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['category'], name='attractions_categor_2f4c97_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['region'], name='attractions_region__c03a58_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['difficulty_level'], name='attractions_difficu_67908a_idx'),
        ),
    ]
