# Generated by Django 4.2.28 on 2026-03-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attraction_deleted_at_attraction_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
