# Generated by Django 4.2.28 on 2026-03-19 08:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
        ('attractions', '0006_alter_attraction_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='attraction',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for SEO and accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='attraction',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Mark as free if no entrance fee'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='attractions', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='entrance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee in USD (DEPRECATED: use price_from)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main/cover image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
