# Generated by Django 4.2.28 on 2026-03-22 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0007_attraction_currency_attraction_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attractions', to=settings.AUTH_USER_MODEL),
        ),
    ]
