# Generated by Django 4.2.28 on 2026-04-06 17:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_attraction_updated_by_alter_attraction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
