# Generated by Django 4.2.28 on 2026-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0009_alter_attraction_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='gyg_location_id',
            field=models.CharField(blank=True, help_text='GetYourGuide location ID for affiliate widget (e.g. 1202)', max_length=20),
        ),
    ]
