# Generated by Django 4.2.28 on 2026-04-19 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_attraction', 'Viewed Attraction'), ('view_region', 'Viewed Region'), ('view_article', 'Viewed Article'), ('search', 'Searched'), ('submit_review', 'Submitted Review'), ('view_itinerary', 'Viewed Itinerary')], db_index=True, max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_userac_user_id_ee37d3_idx'), models.Index(fields=['action', 'created_at'], name='core_userac_action_f04338_idx'), models.Index(fields=['object_type', 'object_id'], name='core_userac_object__ef92cb_idx')],
            },
        ),
    ]
