# Generated by Django 4.2.28 on 2026-03-19 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_days', models.PositiveIntegerField()),
                ('estimated_budget_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total budget in USD', max_digits=10, null=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult'), ('extreme', 'Extreme')], default='moderate', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
                ('featured_attractions', models.ManyToManyField(blank=True, help_text='Main attractions covered in this itinerary', related_name='itineraries', to='attractions.attraction')),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('accommodation_notes', models.TextField(blank=True, help_text='Where to stay, camp, or rest')),
                ('meals_notes', models.TextField(blank=True, help_text='Meal recommendations for the day')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, help_text='Recommended start time', null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Tips, warnings, or special instructions')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_activities', to='attractions.attraction')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary.itineraryday')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['difficulty_level'], name='itinerary_i_difficu_2c8bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['is_public'], name='itinerary_i_is_publ_68de37_idx'),
        ),
    ]
