# Generated by Django 4.2.28 on 2026-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('promo', 'Promotion'), ('maintenance', 'Maintenance')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='When to show this announcement', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='When to hide this announcement', null=True)),
                ('target_url', models.URLField(blank=True, help_text='Optional CTA link')),
                ('target_label', models.CharField(blank=True, help_text='CTA button label', max_length=100)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'ends_at'], name='announcemen_is_acti_0b60ae_idx'), models.Index(fields=['priority'], name='announcemen_priorit_8accd1_idx')],
            },
        ),
    ]
